import React from "react";

function TechnicalProgramCommittee() {

    const technicalProgramCommittee = [
        {name: "Prof. Mridula Gupta", university: "University of Delhi South Campus, New Delhi, India"},
        {name: "Prof. Naveen Kumar", university: "University of Delhi, Delhi, India"},
        {name: "Prof. Veer Bahadur Singh", university: "Jawaharlal Nehru University, New Delhi, India"},
        {name: "Mr. Ajit Kumar", university: "Vice President, Fixed Income Data Technology Group, Morgan Stanley, USA"},
        {name: "Mr. Vikas Sharma", university: "M.D, Sunworks Systems, Gurgaon, India"},
        {name: "Prof. Vikas Saxena", university: "Jaypee University, Noida, India"},
        {name: "Prof. Rakesh Kumar Pandey", university: "Kirorimal College, University of Delhi, Delhi, India"},
        {name: "Prof. Naveen Jain", university: "University of Delhi, New Delhi, India"},
        {name: "Dr. Manish Kumar", university: "Zakir Husain Delhi College, University of Delhi, New Delhi, India"},
        {name: "Dr. D. Vijay Rao", university: "DRDO, India"},
        {name: "Prof. Hema Banati", university: "Dyal Singh College, University of Delhi, India"},
        {name: "Dr. Kanchan Sharma", university: "Indira Gandhi Technical University for Women, Delhi, India"},
        {name: "Dr. Ravi Sony", university: "University of Florida, USA"},
        {name: "Dr. Ruchi Tripathi", university: "Guru Ghasidas Central University, Bilaspur, Chhattisgarh, India"},
        {name: "Dr. Sugandha Sharma", university: "IIT Mumbai, India"},
        {name: "Dr. Amita Kapoor", university: "Founder, NePeur AI, Bengaluru, India"},
        {name: "Dr. Vandana Bhalla", university: "University of Delhi, New Delhi, India"},
        {name: "Dr. Ravneet Kaur", university: "University of Delhi, New Delhi, India"},
        {name: "Dr. Arunesh Singh", university: "Jamia Millia Islamia University, New Delhi, India"},
        {name: "Mr. Anuj Rathi", university: "Synopsys, Noida, India"},
        {name: "Dr. Rajni Bala", university: "University of Delhi, New Delhi, India"},
        {name: "Dr. Charu Agarwal", university: "Galgotia University, Greater Noida, UP, India"},
        {name: "Dr. Ritu Gupta", university: "Guru Gobind Singh IP University, New Delhi, India"},
        {name: "Dr. Rajiv Ranjan Singh", university: "Glasgow Caledonian University, Scotland, UK"},
        {name: "Dr. Sarika Jain", university: "National Institute of Technology, Kurukshetra, Haryana, India"},
        {name: "Dr. Kunti Mishra", university: "Noida Institute of Engineering & Technology, Greater Noida, UP, India"},
        {name: "Dr. Megha Bansal", university: "DDU College, University of Delhi, India"},
        {name: "Ms. Jyoti Maurya", university: "MNNIT Allahabad, Uttar Pradesh, India"},
        {name: "Prof. Rajesh Prasad", university: "UP Technical University, India"},
        {name: "Prof. Arpita Sharma", university: "University of Delhi, New Delhi, India"},
        {name: "Dr. Om Mishra", university: "National Law Institute University, Bhopal, India"},
        {name: "Prof. Anand Pandyan", university: "Keele University, UK"},
        {name: "Prof. Vidya Sudarshan", university: "SUSS Singapore"},
        {name: "Prof. Justin Dauwels", university: "NTU Singapore"},
        {name: "Prof. Mohammad Haider", university: "Saudi Electronic University, Saudi Arabia"},
        {name: "Prof. Suresh Sundaram", university: "IISc Bangalore, India"},
        {name: "Dr. Nidhi", university: "University of Delhi, India"},
        {name: "Dr. Ram Prasad K", university: "VisionCog R&D, India"},
        {name: "Dr. Amira Fahoud", university: "Ministry of Education, Syria"},
        {name: "Dr. Anooshmita Das", university: "Copenhagen, Denmark"},
        {name: "Dr. Ananda Hati", university: "IIT(ISM) Dhanbad, India"},
        {name: "Dr. J C Miraclin Joyce Pamila", university: "GCT Coimbatore, India"},
        {name: "Dr. Rajiv Ratn Saha", university: "IIIT Delhi, India"},
        {name: "Prof. Vikram Bali", university: "JSS Academy of Technical Education, India"},
        {name: "Prof. Bhuvan Unhelkar", university: "University of South Florida Sarasota-Manatee, USA"},
        {name: "Prof. Dinesh K Sharma", university: "University of Maryland Eastern Shore, USA"},
        {name: "Dr. V. Vijaya Saradhi", university: "IIT Guwahati, India"},
        {name: "Dr. Reshma Rastogi", university: "South Asian University, New Delhi, India"},
        {name: "Dr. Sangram Roy", university: "NIT Sikkim, India"},
        {name: "Prof. Asif Ekbal", university: "IIT Patna, India"},
        {name: "Dr. Diksha Shukla", university: "University of Wyoming, USA"},
        {name: "Dr. Anish Kumar Saha", university: "NIT Silchar, India"},
        {name: "Prof. Diptendu Sinha Roy", university: "NIT Meghalaya, India"},
        {name: "Dr. Argha Sarkar", university: "Vishnu Institute of Technology, A.P., India"},
        {name: "Dr. Indrajit Pan", university: "RCC, Kolkata, India"},
        {name: "Dr. Parashjyoti Borah", university: "SoAU, India"},
        {name: "Dr. Preety Singh", university: "LNMIIT Jaipur, India"},
        {name: "Dr. Anil Kumar Vuppala", university: "IIIT Hyderabad, India"},
        {name: "Prof. K. V. Arya", university: "IIIT Gwalior, India"},
        {name: "Dr. Manish Sharma", university: "IITRAM Ahmedabad, India"},
        {name: "Dr. Pushpendra Singh", university: "JNU New Delhi, India"},
        {name: "Dr. Abir J Mondal", university: "NIT Arunachal Pradesh, India"},
        {name: "Prof. Sukumar Nandi", university: "IIT Guwahati, India"},
        {name: "Dr. Anil Kumar", university: "IIITDM Jabalpur, India"},
        {name: "Dr. Jitendra Kumar Verma", university: "Amity University, India"},
        {name: "Dr. Nitin Kumar", university: "National Institute of Technology Uttarakhand, India"},
        {name: "Prof. R.P. Singh", university: "DDUC, University of Delhi, India"},
        {name: "Dr. Yaka Bulo", university: "NIT Arunachal Pradesh, India"},
        {name: "Dr. Anurag Mishra", university: "ABES Engineering College, Ghaziabad, India"},
        {name: "Dr. Barenya B Hazarika", university: "NIT Arunachal Pradesh, India"},
        {name: "Dr. Partha Pratim Roy", university: "IIT Roorkee, India"},
        {name: "Dr. Rajesh Bose", university: "Brainware University, India"},
        {name: "Dr. Sahadev Roy", university: "NIT Arunachal Pradesh, India"},
        {name: "Prof. Vivek Kumar Singh", university: "Delhi University, India"},
        {name: "Prof. Koshy George", university: "SRM University, India"},
        {name: "Dr. N. Padmavathy", university: "Vishnu Institute of Technology, A.P., India"},
        {name: "Dr. Mayuri Kundu", university: "Vishnu Institute of Technology, A.P., India"},
        {name: "Dr. Erenda Perera", university: "SLTC, Sri Lanka"},
        {name: "Dr. Tanmoy Hazra", university: "IIIT Pune, India"},
        {name: "Dr. Mou Dasgupta", university: "NIT Raipur, India"},
        {name: "Dr. Avdhesh Gupta", university: "AKGEC, Ghaziabad, U.P., India"},
        {name: "Dr. Manju L. Joshi", university: "ISIM, Jaipur, India"},
        {name: "Dr. SK Hafizul Islam", university: "IIIT Kalyani, India"},
        {name: "Dr. Mohammad Sajid", university: "Aligarh Muslim University, Aligarh, India"},
        {name: "Dr. Amit Kumar", university: "Rajkiya Engineering College Ambedkar Nagar, India"},
        {name: "Dr. Sunil Kumar Singh", university: "Mahatma Gandhi Central University, Bihar, India"},
        {name: "Dr. Aswini Kumar Patra", university: "NERIST, Arunachal Pradesh, India"},
        {name: "Dr. Siddhi Nath Rajan", university: "IMS Engineering College, Ghaziabad, India"},
        {name: "Dr. J C Miraclin", university: "GCT Coimbatore, India"},
        {name: "Dr. Bobby Sharma", university: "Assam Don Bosco University, India"},
        {name: "Dr. Saroj Kr. Biswas", university: "NIT Silchar, India"},
        {name: "Dr. Abhishek Rawat", university: "IITRAM Ahmedabad, India"},
        {name: "Dr. Yogendra Meena", university: "Delhi University, India"},
        {name: "Dr. Upendra Mishra", university: "IMSEC, India"},
        {name: "Prof. Sanjoy Das", university: "IGNTU Manipur, India"},
        {name: "Dr. Shrawan Kumar", university: "IGNTU Manipur, India"},
        {name: "Dr. Bharti Rana", university: "DU, India"},
        {name: "Dr. Ushamary Sharma", university: "Assam Don Bosco University, India"},
        {name: "Dr. Bharat Richhariya", university: "IIT Indore, India"},
        {name: "Dr. Santosh Kumar", university: "ABES Engineering College, India"},
        {name: "Dr. Alak Majumdar", university: "NIT Arunachal Pradesh, India"},
        {name: "Dr. Anurag Mishra", university: "DDUC, University of Delhi, India"},
        {name: "Dr. Gaurav Baranwal", university: "BHU, Varanasi, India"},
        {name: "Dr. Mainak Mallik", university: "NIT Arunachal Pradesh, India"},
        {name: "Dr. Raghuraj Singh", university: "HBTU Kanpur, India"},
        {name: "Dr. Sanjeev Kumar Metya", university: "NIT Arunachal Pradesh, India"},
        {name: "Dr. Bharti Rana", university: "University of Delhi, India"},
        {name: "Dr. A. Vanav Kumar", university: "NIT Arunachal Pradesh, India"},
        {name: "Dr. Bubu Bhuyan", university: "NEHU Shillong, India"},
        {name: "Dr. Sufal Das", university: "NEHU Shillong, India"},
        {name: "Dr. Yang Saring", university: "NIT Arunachal Pradesh, India"},
        {name: "Dr. Swapan Kumar Mondal", university: "Kalyani University, WB, India"},
        {name: "Dr. M. Berlin", university: "NIT Arunachal Pradesh, India"},
        {name: "Dr. Baisakhi Das", university: "IEM, Kolkata, India"},
        {name: "Dr. C Koner", university: "BC Roy Engineering College, WB, India"},
        {name: "Dr. Ditipriya Sinha", university: "NIT Patna, India"},
        {name: "Dr. Natarajan Narayanan", university: "MCET, Pollachi, India"},
        {name: "Dr. Somya Goyal", university: "Manipal University Jaipur, India"},
        {name: "Dr. Hemant Kumar Meena", university: "MNIT Jaipur, India"},
        {name: "Dr. Subhadeep Mukhopadhyay", university: "NIT Arunachal Pradesh, India"},
        {name: "Dr. Abhishek Gupta", university: "Shri Mata Vaishno Devi University, India"},

        { name: "Masira Kulkarni", university: "G H Raisoni College of Engineering and research, Pune" },
        { name: "Dr. Padmavathy N", university: "Vishnu Institute of Technology, Bhimavaram" },
        { name: "Sonam Gupta", university: "Ajay Kumar Garg Enginnering College" },
        { name: "Aditya Dev Mishra", university: "Galgotias College of Engineering and Technology, Greater Noida" },
        { name: "Dr. Smita", university: "Galgotias University, Greater Noida" },
        { name: "Dr Gulab Sah", university: "National Institute of Technology Delhi" },
        { name: "Dr Mohammad Sajid", university: "Aligarh Muslim University, Aligarh" },
        { name: "Rachana Singh Sisodia", university: "G.L. Bajaj Institute of Technology & Management" },
        { name: "Himanshu Tiwari", university: "JIMS Engineering Management Technical Campus Greater Noida" },
        { name: "Dr Greetta Pinheiro", university: "Bennett University" },
        { name: "Dr Ashish Singh Parihar", university: "PDPM IIITDM Jabalpur (MP)" },
        { name: "Dr. Gunjan Verma", university: "GL BAJAJ INSTITUTE OF TECHNOLOGY AND MANAGEMENT" },
        { name: "Dr Sumit Kumar", university: "Rajan Mamta Degree College" },
        { name: "Dr. Mohd. Nazim", university: "NIET, Greater Noida" },
        { name: "Sameer Awasthi", university: "Bansal Institute of Engineering and technology Lucknow" },
        { name: "Prof. Naren J", university: "MS Ramaiah University of Applied Sciences" },
        { name: "Dr. Mukta Sandhu", university: "Shri Vishwakarma Skill University Palwal" },
        { name: "SUJIT BISWAS", university: "Techno Institute of Engineering & Management, Banipur" },
        { name: "Saikat Samanta", university: "Manipal University Jaipur" },
        { name: "Dr Shanvendra Rai", university: "Nirma University" },
        { name: "Dr Samta Jain Goyal", university: "Amity University Gwalior" },
        { name: "Chandni Agarwal", university: "GLA University" },
        { name: "Rajat Gera", university: "CMR university" },
        { name: "Bhawna Sachdeva", university: "Greater Noida institute of engineering and technology" },
        { name: "Lalita Chaudhary", university: "Bennett university" },
        { name: "Dr Jyoti Singh Kirar", university: "Jawaharlal Nehru University, New Delhi" },
        { name: "Abhishek Kesharwani", university: "ABES Engineering college, Ghaziabad" },
        { name: "Dr Pramod Kumar Soni", university: "Galgotias University Greater Noida UP" },
        { name: "Dr Brij Bhushan Sharma", university: "Shoolini University of Biotechnology and Management Sciences" },
        { name: "Dr. Veena Mittal", university: "GCET Greater Noida" },
        { name: "Dr Pancham Singh", university: "AKGEC, Ghaziabad" },
        { name: "Dr Nishant Jain", university: "Jaypee University of Information Technology" },
        { name: "Ishan Ayus", university: "Siksha O Anusandhan University, Bhubaneswar" },
        { name: "Dr. Aatif Jamshed", university: "KIET Group of Institutions" },
        { name: "Dr Argha Sarkar", university: "REVA University Bengaluru" },
        { name: "Dr Neha Goyal", university: "MMICTBM, MM(DU), Mullana" },
        { name: "Dr Arti Patle", university: "G H Raisoni College of Engineering and Management Pune" },
        { name: "Mr. Kalyanjit Hatibaruah", university: "Flugelsoft Group" },

        { name: "Dr. Sugandhi K", university: "Hindustan Institute of Technology and Science" },
        { name: "Dr. Dheeraj Sonkhla", university: "Himachal Pradesh University, Shimla" },
        { name: "Dr. Surendra Kumar Gupta", university: "PEC Chandigarh" },
        { name: "Dr. Falguni Sharma", university: "Vivekanand Global University" },
        { name: "Dr. Avdhesh Gupta", university: "Ajay Kumar Garg Engineering College" },
        { name: "Dr. Nancy Agarwal", university: "Galgotias University" },
        { name: "Dr Gurmeet Singh", university: "GTBIT-GGSIPU" }

    ];


    console.log(technicalProgramCommittee.length);

    return (
        <section
            id="Technical Program Committee"
            className="mb-8 flex-col rounded-md text-base-content w-full flex items-center">

            <div className="max-w-[1100px] flex flex-col items-center">

                <h2 className="mb-8 text-4xl font-playfair font-bold  text-primary text-center">Technical Program
                    Committee</h2>
                <div className="flex flex-row flex-wrap gap-4 justify-center">
                    {technicalProgramCommittee.map(member => <div
                        className="relative bg-base-200 p-2 w-full max-w-[90%] md:max-w-[270px] hover:rounded-lg hover:bottom-0.5 hover:shadow-sm transition-all duration-300">
                        <p className="font-medium underline">{member.name}</p>
                        <p className="font-thin">{member.university}</p>
                    </div>)}
                </div>
            </div>

        </section>
    )
}

    export default TechnicalProgramCommittee;